name: Coverity on Polaris with GitHub Hosted Runner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: [self-hosted, coverity]
    
    env:
      POLARIS_URL: ${{ secrets.POLARIS_URL }}
      POLARIS_ACCESS_TOKEN: ${{ secrets.POLARIS_ACCESS_TOKEN }}
      SECURITY_GATE_ARGS: --new
      SYNOPSYS_GITHUB_TOOLS_REPO: https://github.com/synopsys-sig-community/synopsys-github-tools

    steps:
      - uses: actions/checkout@v2
      
      - name: Cache Coverity on Polaris Downloads
        id: synopsys-cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.synopsys
          key: synopsys-cache-ubuntu

      - name: Download and configure Polaris CLI
        run: |
          curl -LsS -o polaris.zip $POLARIS_URL/api/tools/polaris_cli-linux64.zip
          unzip -j -d polaris-cli polaris.zip
          ./polaris-cli/polaris --persist-config --co capture.build.buildCommands="null" --co capture.build.cleanCommands="null" --co capture.fileSystem="null" --co capture.coverity.autoCapture="enable" --co            serverUrl=$POLARIS_URL configure

      - name: Coverity Scan (Full analysis)
        if: ${{github.event_name == 'push'}}
        run: ./polaris-cli/polaris analyze -w

      - name: Get Synopsys GitHub Tools
        run: |
          git clone -q --depth 1 $SYNOPSYS_GITHUB_TOOLS_REPO
          pip3 install --upgrade pandas requests==2.26.0 urllib3==1.26.7 jsonapi-requests==0.6.2 tenacity==6.2.0
        
      - name: Export Coverity Results to SARIF
        run: python3 ./synopsys-github-tools/github-export-polaris-issues.py --debug 9
        
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: synopsys-coverity-github-sarif.json
